### ISSUE TITLE
Mouse cursor not working

### ISSUE THREAD

**Issue by FrancoisPerez** [bitcraft/tailor#3]
Hello,

It seems like you absolutely need a touchscreen to use this program.
Any attemps to run it without a touchscreen will guide you to a black screen with a single button you cannot click.
When you say it is "mouse capable" is there anything that must be activated ?

**Comment by bitcraft** [comment]
I'lll add a config option to show the cursor :D

**Comment by FrancoisPerez** [comment]
That is one quick answer :)
Somehow, I feel like it is not only the cursor that is hidden but the entire "mouse" concept which doesn't exist. (I tried clicking randomly on every part of the screen to locate the cursor but the button stays unclickable)

**Comment by bitcraft** [comment]
it is possible the your camera is undetected as well  Ive used a mouse
before no problem.  I'll add the option later today.

**Comment by FrancoisPerez** [comment]
Apparently the camera is correctly detected because I get a picture when I do a `fswebcam test.jpg`
I tried to position my cursor at the bottom center of the screen and wait for the program to start. When the black screen+button appears, I cannot click (nor ctrl+click) anywhere

**Comment by bitcraft** [comment]
Francois, I've taken a moment to test everything and I can't seem to reproduce the issue.  I've made just a few changes to everything, including the documentation.  Please pull the latest changes and see if that helps.

**Comment by FrancoisPerez** [comment]
Hi,
Very good commit :)
I finally ended up making the mouse cursor appear by editing the [module] section of kivy's config.ini and adding 
`touchring = show_cursor=true`

So now the cursor appears, but as soon as I click on the button at the bottom, the entire app freezes

**Comment by bitcraft** [comment]
Thanks for that information; I'll add it to the readme.  As for the camera, do you have the camera plugin changed to "opencv" in service.json?

**Comment by bitcraft** [comment]
I also just added basic support for using pygame as the camera provider.  It may help you as well.

**Comment by FrancoisPerez** [comment]
`pygame `is definitely the way to go ! It is working like a charm (without the pain of installing `opencv`).
Can you describe how to start the kiosk UI ?

**Comment by bitcraft** [comment]
If you use run_local.py, then the kiosk should activate automatically.

**Comment by FrancoisPerez** [comment]
Ok so that's it ! I was expecting ways of sharing the pictures through twitter but apparently it is not implemented yet.
I'll be looking soon to implement a FTP upload or something similar + twilio integration

**Comment by bitcraft** [comment]
Twitter was a working feature a long time ago. It's been untested for a long time though.  I'll add some instructions.  As for ftp, I just run sshd and pull files that way. There is also the http server... Any suggestions are welcome.

**Comment by FrancoisPerez** [comment]
Two more questions : 
I have been trying to setup a PiCamera module instead of my C920 camera (which pulls to much power from the RPI) but it seems like we can't use PiCamera with Pygame.
Do you think the pygame code is easily adaptable for use with picamera ?
Also, I keep having freezes with the RPI becoming unresponsive. Any idea where this come from ?

**Comment by bitcraft** [comment]
Good to hear from you again.  Pygame...moves very slow and patches can be difficult to be merged.  Personally, I have some knowledge of the source code, but I'm not familiar with the camera module.  If you know some C, then it shouldn't be difficult if there is a lib for that camera somewhere, but you may have to maintain and compile pygame yourself...If pygame doesn't support it, perhaps you can let me know of another library that does, and I will see if I can support it.

- What is happening on your RPI?  What model (and how much RAM?).
- How much time until the problem happens?

**Comment by FrancoisPerez** [comment]
Hi !
I looks to heavy for my poor knowledge in C :), I'll keep with the webcam then.

I own a RPI 3 (the latest one), so I think it is something like 1G RAM.
It is not a question of time but more of an issue with Kivy I think
Here is the issue on a video : https://www.youtube.com/watch?v=1YekU5Wm57w

**Comment by bitcraft** [comment]
Thanks for the video, it was nice to see it launch.  Does this happen all the time?  Or just sometimes?  (I realize not it is not the RAM issues, perhaps something else...)

**Comment by FrancoisPerez** [comment]
It is all the time.
As you can see, the galaxy.png picture won't load in the background as well.

**Comment by FrancoisPerez** [comment]
Would you mind sharing a video of your own version, to see how it is supposed to work ?

**Comment by bitcraft** [comment]
@FrancoisPerez Sorry, I realize its been over a year.... I have a video if you are still interested.

https://www.youtube.com/watch?v=q-pIkZ7cbBY
